package exception_004;

class UserException extends Exception {

    void Method() {

        System.out.println("Мое Исключение!");
    }
}
